
package interfaces;

import beans.ConsultaFerragem;
import dao.ConsultaFerragemDAO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class frmConsultaFerragem extends javax.swing.JInternalFrame {

    private ConsultaFerragemDAO consultaferragemDAO;
    
    public frmConsultaFerragem() {
        initComponents();
        
        this.consultaferragemDAO = new ConsultaFerragemDAO();
        
        ArrayList<ConsultaFerragem> consultaFerragem = new ArrayList<ConsultaFerragem>();

        consultaFerragem = this.consultaferragemDAO.getFerragemByLista();

        DefaultTableModel tabela = (DefaultTableModel) tblFerragem.getModel();

        tabela.setNumRows(0);
        for (ConsultaFerragem con : consultaFerragem) {

            if (con != null) {
                Object[] obj = new Object[]{
                    con.getIdferragem(),
                    con.getIdproduto(),
                    con.getDescricao(),
                    con.getNome(),
                    con.getData()
                };
                tabela.addRow(obj);
            }
        } 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFerragem = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Consulta Ferragem");

        tblFerragem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Ferragem", "Id Produto", "Descrição", "Usuário", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFerragem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(238, 238, 238))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFerragem;
    // End of variables declaration//GEN-END:variables
}
