/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import beans.TelaPedido;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import calculodeferragem.CalculoDeFerragem;
import dao.PedidoDAO;
import java.math.BigDecimal;
import static utils.ControleForms.mpedidoferragem;
import javax.swing.table.DefaultTableModel;

/*
 * @author Aluno
 */
public class frmPedido extends javax.swing.JInternalFrame
{

  private boolean status;

  private PedidoDAO pedidoDAO;

  private double varQtdeBarraColuna;
  private double varEstriboTotal;
  private double varQtdeEstribo;
  private double varQtdeBarraEstribo;
  private double varQtdeArame;
  private String varTipo;

  private int varIdFerragem;
  private int varIdProduto;

  private int contaFerragem;
  private int contaItens;

  private CalculoDeFerragem calc;
  // private Object pedidoDAO;

  public frmPedido()
  {
    initComponents();
    buttonGroup1.add(rbArame);
    buttonGroup1.add(rbEstribo);
    buttonGroup1.add(rbVergalhao);
    buttonGroup1.add(rbVergalhaoAdicional);
    estadoInicial();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        txtQtdeColunas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtComprimentoColuna = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEstriboAltura = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEspacoEstribo = new javax.swing.JTextField();
        txtMensagem = new javax.swing.JTextField();
        txtPedido = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        txtEstriboLargura = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        ComboStatus = new javax.swing.JComboBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbItemProduto = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbFerragem = new javax.swing.JTable();
        txtIdCliente = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtIdProduto = new javax.swing.JTextField();
        txtDescricaoProduto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtQtdeFerroColuna = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnAddProduto = new javax.swing.JButton();
        rbVergalhao = new javax.swing.JRadioButton();
        rbEstribo = new javax.swing.JRadioButton();
        rbArame = new javax.swing.JRadioButton();
        rbVergalhaoAdicional = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnNovoFerragem = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        txtDataEntrega = new javax.swing.JTextField();
        txtObservacao = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(968, 651));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel4.setText("Qtde Colunas (Un) :");

        txtQtdeColunas.setText("1");
        txtQtdeColunas.setMinimumSize(new java.awt.Dimension(28, 28));
        txtQtdeColunas.setName(""); // NOI18N
        txtQtdeColunas.setPreferredSize(new java.awt.Dimension(50, 28));
        txtQtdeColunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdeColunasActionPerformed(evt);
            }
        });

        jLabel5.setText("Comprimento Coluna (Mts) :");

        txtComprimentoColuna.setText("12");
        txtComprimentoColuna.setMinimumSize(new java.awt.Dimension(28, 28));
        txtComprimentoColuna.setName(""); // NOI18N
        txtComprimentoColuna.setPreferredSize(new java.awt.Dimension(50, 28));

        jLabel6.setText("Estribo Altura (cm):");

        txtEstriboAltura.setText("20");
        txtEstriboAltura.setMinimumSize(new java.awt.Dimension(28, 28));
        txtEstriboAltura.setName(""); // NOI18N
        txtEstriboAltura.setPreferredSize(new java.awt.Dimension(50, 28));

        jLabel7.setText("Estribo Largura (cm):");

        jLabel9.setText("Espaçamento entre os estribos (cm):");

        txtEspacoEstribo.setText("20");
        txtEspacoEstribo.setMinimumSize(new java.awt.Dimension(28, 28));
        txtEspacoEstribo.setName(""); // NOI18N
        txtEspacoEstribo.setPreferredSize(new java.awt.Dimension(50, 28));

        txtMensagem.setEditable(false);
        txtMensagem.setForeground(new java.awt.Color(204, 0, 0));
        txtMensagem.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMensagemActionPerformed(evt);
            }
        });

        txtPedido.setEditable(false);
        txtPedido.setText("1");
        txtPedido.setMinimumSize(new java.awt.Dimension(28, 28));
        txtPedido.setName(""); // NOI18N
        txtPedido.setPreferredSize(new java.awt.Dimension(50, 28));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pedido");

        txtEstriboLargura.setText("20");
        txtEstriboLargura.setMinimumSize(new java.awt.Dimension(28, 28));
        txtEstriboLargura.setName(""); // NOI18N
        txtEstriboLargura.setPreferredSize(new java.awt.Dimension(50, 28));

        jLabel41.setText("Status :");

        ComboStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aberto", "Fechado", "Entregue" }));

        tbItemProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Produto", "Tipo", "Qtde Estribo (Pçs)", "Total Barra / Arame kg"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tbItemProduto);
        if (tbItemProduto.getColumnModel().getColumnCount() > 0) {
            tbItemProduto.getColumnModel().getColumn(0).setResizable(false);
            tbItemProduto.getColumnModel().getColumn(1).setResizable(false);
            tbItemProduto.getColumnModel().getColumn(2).setResizable(false);
            tbItemProduto.getColumnModel().getColumn(3).setResizable(false);
        }

        tbFerragem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Qtde Colunas", "Comprimento", "Altura Estribo", "Largura Estribo", "Espaçamento Estribos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tbFerragem);
        if (tbFerragem.getColumnModel().getColumnCount() > 0) {
            tbFerragem.getColumnModel().getColumn(0).setResizable(false);
            tbFerragem.getColumnModel().getColumn(1).setResizable(false);
            tbFerragem.getColumnModel().getColumn(2).setResizable(false);
            tbFerragem.getColumnModel().getColumn(3).setResizable(false);
            tbFerragem.getColumnModel().getColumn(4).setResizable(false);
        }

        txtIdCliente.setText("1");
        txtIdCliente.setToolTipText("Enter para procurar cliente");
        txtIdCliente.setMinimumSize(new java.awt.Dimension(28, 28));
        txtIdCliente.setName(""); // NOI18N
        txtIdCliente.setPreferredSize(new java.awt.Dimension(50, 28));
        txtIdCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdClienteFocusLost(evt);
            }
        });

        jLabel42.setText("Cliente:");

        txtNomeCliente.setEditable(false);
        txtNomeCliente.setMinimumSize(new java.awt.Dimension(28, 28));
        txtNomeCliente.setName(""); // NOI18N
        txtNomeCliente.setPreferredSize(new java.awt.Dimension(50, 28));
        txtNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeClienteActionPerformed(evt);
            }
        });

        jLabel43.setText("Data:");

        txtData.setMinimumSize(new java.awt.Dimension(28, 28));
        txtData.setName(""); // NOI18N
        txtData.setPreferredSize(new java.awt.Dimension(50, 28));
        txtData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataFocusLost(evt);
            }
        });
        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Produto :");

        txtIdProduto.setText("1");
        txtIdProduto.setMinimumSize(new java.awt.Dimension(28, 28));
        txtIdProduto.setPreferredSize(new java.awt.Dimension(50, 28));
        txtIdProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdProdutoFocusLost(evt);
            }
        });
        txtIdProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProdutoActionPerformed(evt);
            }
        });

        txtDescricaoProduto.setEditable(false);
        txtDescricaoProduto.setMinimumSize(new java.awt.Dimension(28, 28));
        txtDescricaoProduto.setPreferredSize(new java.awt.Dimension(50, 28));
        txtDescricaoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoProdutoActionPerformed(evt);
            }
        });

        jLabel10.setText("Quantidade Ferros na Coluna :");

        txtQtdeFerroColuna.setText("4");
        txtQtdeFerroColuna.setToolTipText("Digite Qtde de Vergalhão");
        txtQtdeFerroColuna.setMinimumSize(new java.awt.Dimension(28, 28));
        txtQtdeFerroColuna.setPreferredSize(new java.awt.Dimension(50, 28));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Inserção de produtos que compoem a ferragem");

        btnAddProduto.setBackground(new java.awt.Color(255, 255, 255));
        btnAddProduto.setText("Adicionar");
        btnAddProduto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdutoActionPerformed(evt);
            }
        });

        rbVergalhao.setText("Vergalhao");

        rbEstribo.setText("Estribo");

        rbArame.setText("Arame");

        rbVergalhaoAdicional.setText("Vergalhao Adicional");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbVergalhao)
                        .addGap(8, 8, 8)
                        .addComponent(rbEstribo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbArame)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbVergalhaoAdicional)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQtdeFerroColuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddProduto)
                        .addGap(60, 60, 60))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDescricaoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtQtdeFerroColuna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddProduto)
                    .addComponent(rbVergalhao)
                    .addComponent(rbEstribo)
                    .addComponent(rbArame)
                    .addComponent(rbVergalhaoAdicional))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/838_32x32.png"))); // NOI18N
        btnNovo.setText("Novo Pedido");
        btnNovo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/8428_32x32.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/8408_32x32.png"))); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/8412_32x32.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/8398_32x32.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnNovoFerragem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/838_32x32.png"))); // NOI18N
        btnNovoFerragem.setText("Nova Ferragem");
        btnNovoFerragem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNovoFerragem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoFerragemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovoFerragem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNovoFerragem)
                .addGap(18, 18, 18)
                .addComponent(btnAlterar)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addGap(18, 18, 18)
                .addComponent(btnDeletar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel44.setText("Data  Entrega :");

        txtDataEntrega.setMinimumSize(new java.awt.Dimension(28, 28));
        txtDataEntrega.setName(""); // NOI18N
        txtDataEntrega.setPreferredSize(new java.awt.Dimension(50, 28));
        txtDataEntrega.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataEntregaFocusLost(evt);
            }
        });

        txtObservacao.setForeground(new java.awt.Color(0, 0, 153));
        txtObservacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtObservacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObservacaoActionPerformed(evt);
            }
        });

        jLabel45.setText("Observação : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtObservacao))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 5, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtQtdeColunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtComprimentoColuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtEstriboLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtEstriboAltura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtEspacoEstribo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel43)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(317, 317, 317)
                                        .addComponent(jLabel41)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ComboStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel42)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane5))
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtMensagem)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel41))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(ComboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel42))
                            .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtQtdeColunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtComprimentoColuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtEstriboLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtEstriboAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEspacoEstribo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel43)
                                    .addComponent(jLabel44))))
                        .addGap(11, 11, 11)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(txtMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void estadoInicial()
  {

    txtMensagem.setEditable(false);
    txtPedido.setEditable(false);
    txtIdCliente.setEditable(false);
    txtNomeCliente.setEditable(false);
    txtQtdeColunas.setEditable(false);
    txtComprimentoColuna.setEditable(false);
    txtEstriboLargura.setEditable(false);
    txtEstriboAltura.setEditable(false);
    txtEspacoEstribo.setEditable(false);
    txtData.setEditable(false);
    txtDataEntrega.setEditable(false);
    txtIdProduto.setEditable(false);
    txtQtdeFerroColuna.setEditable(false);
    txtObservacao.setEditable(false);

    btnAlterar.setEnabled(false);
    btnBuscar.setEnabled(true);
    btnDeletar.setEnabled(false);
    btnNovo.setEnabled(true);
    btnNovoFerragem.setEnabled(false);
    btnCancelar.setEnabled(false);

    btnAddProduto.setEnabled(false);

    //txtIdProduto.setText("");    
    rbVergalhao.setSelected(true);
    rbEstribo.setEnabled(false);
    rbArame.setEnabled(false);
    rbVergalhaoAdicional.setEnabled(false);

  }

  /*private void verificaProduto()
   {
   TelaPedido p = this.pedidoDAO.getConferencia(varIdFerragem, varIdProduto);
    
   if (p != null) {
   txtMensagem.setText("Produto já inserido nessa ferragem !");
   txtIdProduto.setText("");
   txtDescricaoProduto.setText("");
   txtIdProduto.grabFocus();
   }       
   }*/
  private String getDateTime()
  {
    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    Date date = new Date();
    return dateFormat.format(date);
  }

  private String getDate()
  {
    DateFormat dateFormat = new SimpleDateFormat();
    Date date = new Date();
    return dateFormat.format(date);
  }

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNovoActionPerformed
    {//GEN-HEADEREND:event_btnNovoActionPerformed
      // TODO add your handling code here:
      txtMensagem.setText("");

      txtIdCliente.setEditable(true);
      txtQtdeColunas.setEditable(true);
      txtComprimentoColuna.setEditable(true);
      txtEstriboLargura.setEditable(true);
      txtEstriboAltura.setEditable(true);
      txtEspacoEstribo.setEditable(true);
      txtIdProduto.setEditable(true);
      txtQtdeFerroColuna.setEditable(true);
      txtDataEntrega.setEditable(true);
      txtData.setEditable(true);

      btnNovo.setEnabled(false);
      btnCancelar.setEnabled(true);
      btnBuscar.setEnabled(false);
      btnAddProduto.setEnabled(true);

      status = true;

// txtIdFerragem.setText(String.valueOf(this.ferragemDAO.getFerragemByMaxId()));

    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBuscarActionPerformed
    {//GEN-HEADEREND:event_btnBuscarActionPerformed
      // TODO add your handling code here:

      txtMensagem.setText("");

      //    int idferragem = Integer.parseInt(JOptionPane.showInputDialog("Digite o codigo da busca!"));
      // Ferragem u = this.ferragemDAO.getFerragemById(idferragem);
      //    u = this.ferragemDAO.getFerragemById(idferragem);
      //   if (u == null)
      //   {
      //JOptionPane.showMessageDialog(null, "Usuario não encontrado");
      txtMensagem.setText("Ferragem não encontrado !");

  //      } else
      //     {
      //        txtIdFerragem.setText(String.valueOf(u.getIdFerragem()));
      //     txtQtdeColunas.setText(String.valueOf(u.getQtdeFerragem()));
      //        txtComprimentoColuna.setText(String.valueOf(u.getComprimento()));
      //          txtDiametroEstribo.setText(u.getDiametro());   // já esta em string
      //         txtEspacoEstribo.setText(String.valueOf(u.getEspacoEstribo()));
      //         txtEstriboAltura.setText(String.valueOf(u.getEstriboAltura()));
      //         txtEstriboLargura.setText(String.valueOf(u.getEstriboLargura()));
      //       txtIdFerragem.setText(String.valueOf(u.getIdFerragem()));
      //       txtIdProduto.setText(String.valueOf(u.getIdProduto()));
      //        txtUsuarioLogado.setText(String.valueOf(u.getIdUsuario()));
      //         txtQtdeColunas.setText(String.valueOf(u.getQtdeFerragem()));
      //         txtQtdeFerroColuna.setText(String.valueOf(u.getQtdeFerro()));
      //       txtTotalEstribo.setText(String.valueOf(u.calculoTotalEstribo()));
      //      txtTotalBarrasColuna.setText(String.valueOf(u.calculoQuantidadeBarrasColunas()));
      //       txtTotalBarrasEstribo.setText(String.valueOf(u.calculoQuantidadeBarrasEstribos()));
      //       txtTotalArame.setText(String.valueOf(u.calculoQuantidadeArames()));
      //         txtTotalQtdeEstribos.setText(String.valueOf(u.calculoQtdeEstribos()));
      //       btnCancelar.setEnabled(true);
      //       btnNovo.setEnabled(false);
      //         btnAlterar.setEnabled(true);
      //         btnDeletar.setEnabled(true);
      // Produto p = new Produto();
      //      int idproduto = Integer.parseInt(txtIdProduto.getText());
      //         Produto p = this.produtoDAO.getProdutoById(idproduto);
      //        if (p == null)
      //        {
      //             txtMensagem.setText("Produto não encontrado !");
      //        } else
      //         {
      //            txtDescricaoProduto.setText(p.getDescricao());
      //        }
      // }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtDescricaoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoProdutoActionPerformed
      // TODO add your handling code here:
      txtMensagem.setText("");
    }//GEN-LAST:event_txtDescricaoProdutoActionPerformed

    private void txtIdProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdProdutoFocusLost
      // TODO add your handling code here:
      int idproduto = Integer.parseInt(txtIdProduto.getText());
      //   Produto p = this.produtoDAO.getProdutoById(idproduto);

    }//GEN-LAST:event_txtIdProdutoFocusLost

    private void txtMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMensagemActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_txtMensagemActionPerformed

    private void txtIdClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdClienteFocusLost
      // TODO add your handling code here:
    }//GEN-LAST:event_txtIdClienteFocusLost

    private void txtNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeClienteActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeClienteActionPerformed

    private void txtDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataFocusLost
      // TODO add your handling code here:
    }//GEN-LAST:event_txtDataFocusLost

    private void btnAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdutoActionPerformed

      txtIdCliente.setEditable(false);
      txtQtdeColunas.setEditable(false);
      txtComprimentoColuna.setEditable(false);
      txtEstriboLargura.setEditable(false);
      txtEstriboAltura.setEditable(false);
      txtEspacoEstribo.setEditable(false);
      txtData.setEditable(false);
      txtDataEntrega.setEditable(false);
      txtQtdeFerroColuna.setEditable(false);

      if (txtIdProduto.getText() != "")
      {
        txtMensagem.setText("Produto precisa ser inserido !");
        txtIdProduto.setText("");
        txtDescricaoProduto.setText("");
        txtIdProduto.grabFocus();
      }

//verificaProduto();
      TelaPedido p = this.pedidoDAO.getConferencia(varIdFerragem, varIdProduto);

      if (p != null)
      {
        txtMensagem.setText("Produto já inserido nessa ferragem !");
        txtIdProduto.setText("");
        txtDescricaoProduto.setText("");
        txtIdProduto.grabFocus();
      }

      if (rbVergalhao.isSelected() == true)
      {

        varQtdeBarraColuna = calculoQtdeBarrasColunas((Double.parseDouble(txtQtdeColunas.getText())), (Double.parseDouble(txtQtdeFerroColuna.getText())), (Integer.parseInt(txtComprimentoColuna.getText())));
        //JOptionPane.showMessageDialog(null, "Qtde Barra Coluna" + varQtdeBarraColuna);
        varTipo = "VERGALHAO";

        //**************************************************
        DefaultTableModel tabelaFerragem = (DefaultTableModel) tbFerragem.getModel();
        tabelaFerragem.setNumRows(contaFerragem);
        Object[] obj = new Object[]
        {
          txtQtdeColunas.getText(), txtComprimentoColuna.getText(), txtEstriboAltura.getText(), txtEstriboLargura.getText(), txtEspacoEstribo.getText()
        };
        tabelaFerragem.addRow(obj);
        contaFerragem++;

        //**************************************************
        DefaultTableModel tabelaItens = (DefaultTableModel) tbItemProduto.getModel();
        tabelaItens.setNumRows(contaItens);
        Object[] obj2 = new Object[]
        {
          txtIdProduto.getText(), varTipo, null, varQtdeBarraColuna
        };
        tabelaItens.addRow(obj2);
        contaItens++;

        btnCancelar.setEnabled(false);
        btnNovo.setEnabled(false);
        rbEstribo.setEnabled(true);
        rbEstribo.setSelected(true);
        rbVergalhao.setEnabled(false);

        txtIdProduto.setText("");

        // varIdFerragem = (buscar codigo ferragem)
        varIdFerragem = 1; //temporario
        varIdProduto = Integer.parseInt(txtIdProduto.getText());

      }

      else if (rbEstribo.isSelected() == true)
      {
        //estribo

        varEstriboTotal = calculoTotalEstribo((Double.parseDouble(txtEstriboAltura.getText())), (Double.parseDouble(txtEstriboAltura.getText())));
        varQtdeEstribo = calculoQtdeEstribos(Double.parseDouble(txtComprimentoColuna.getText()), Double.parseDouble(txtEspacoEstribo.getText()), Double.parseDouble(txtQtdeColunas.getText()));
        varQtdeBarraEstribo = calculoQtdeBarrasEstribos(Double.parseDouble(txtComprimentoColuna.getText()), Double.parseDouble(txtEspacoEstribo.getText()), Double.parseDouble(txtQtdeColunas.getText()), varEstriboTotal);
        //JOptionPane.showMessageDialog(null, "Estribo Total" + varEstriboTotal + "Qtde Estribo" + varQtdeEstribo + "Qtde Barra Estribo" + varQtdeBarraEstribo);
        varTipo = "ESTRIBO";

        //**************************************************
        DefaultTableModel tabelaItens = (DefaultTableModel) tbItemProduto.getModel();
        tabelaItens.setNumRows(contaItens);
        Object[] obj = new Object[]
        {
          txtIdProduto.getText(), varTipo, varQtdeEstribo, varQtdeBarraEstribo
        };
        tabelaItens.addRow(obj);
        contaItens++;

        rbArame.setEnabled(true);
        rbArame.setSelected(true);

        rbEstribo.setEnabled(false);
        rbVergalhao.setEnabled(false);
        rbVergalhaoAdicional.setEnabled(false);
        txtIdProduto.setText("");

        varIdFerragem = 1; //temporario
        varIdProduto = Integer.parseInt(txtIdProduto.getText());

      }
      else if (rbArame.isSelected() == true)
      {
        // arame

        varQtdeArame = calculoQtdeArames(Double.parseDouble(txtComprimentoColuna.getText()), Double.parseDouble(txtEspacoEstribo.getText()), Double.parseDouble(txtQtdeFerroColuna.getText()), Double.parseDouble(txtQtdeColunas.getText()));
        //JOptionPane.showMessageDialog(null, "Qtde Arame" + varQtdeArame);
        varTipo = "ARAME";

        //**************************************************
        DefaultTableModel tabelaArames = (DefaultTableModel) tbItemProduto.getModel();
        tabelaArames.setNumRows(contaItens);
        Object[] objArame = new Object[]
        {
          txtIdProduto.getText(), varTipo, null, varQtdeArame
        };
        tabelaArames.addRow(objArame);
        contaItens++;

        rbVergalhaoAdicional.setEnabled(true);
        rbVergalhaoAdicional.setSelected(true);

        rbArame.setEnabled(false);
        rbEstribo.setEnabled(false);
        rbVergalhao.setEnabled(false);

        btnNovoFerragem.setEnabled(true);
        txtIdProduto.setText("");
        txtQtdeFerroColuna.setEditable(true);
        txtQtdeFerroColuna.setText("");

        varIdFerragem = 1; //temporario
        varIdProduto = Integer.parseInt(txtIdProduto.getText());
      }
      else if (rbVergalhaoAdicional.isSelected() == true)
      {
        varQtdeBarraColuna = calculoQtdeBarrasColunas((Double.parseDouble(txtQtdeColunas.getText())), (Double.parseDouble(txtQtdeFerroColuna.getText())), (Integer.parseInt(txtComprimentoColuna.getText())));
        //JOptionPane.showMessageDialog(null, "Qtde Barra Coluna" + varQtdeBarraColuna);
        varTipo = "ADICIONAL";

        //**************************************************
        DefaultTableModel tabelaItens = (DefaultTableModel) tbItemProduto.getModel();
        tabelaItens.setNumRows(contaItens);
        Object[] obj2 = new Object[]
        {
          txtIdProduto.getText(), varTipo, null, varQtdeBarraColuna
        };
        tabelaItens.addRow(obj2);
        contaItens++;

        txtIdProduto.setText("");
        txtQtdeFerroColuna.setText("");

        varIdFerragem = 1; //temporario
        varIdProduto = Integer.parseInt(txtIdProduto.getText());

      }


    }//GEN-LAST:event_btnAddProdutoActionPerformed

  private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosing
  {//GEN-HEADEREND:event_formInternalFrameClosing
    // TODO add your handling code here:
    mpedidoferragem = 0;
  }//GEN-LAST:event_formInternalFrameClosing

    private void txtQtdeColunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdeColunasActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdeColunasActionPerformed

    private void txtDataEntregaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataEntregaFocusLost
      // TODO add your handling code here:
    }//GEN-LAST:event_txtDataEntregaFocusLost

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
      // TODO add your handling code here:
      txtMensagem.setText("");

      txtPedido.setEditable(false);
      //txtUsuarioLogado.setText(frmSenha.UsuarioLogado);

      txtIdCliente.setEditable(true);
      txtQtdeColunas.setEditable(true);
      txtComprimentoColuna.setEditable(true);
      txtEstriboLargura.setEditable(true);
      txtEstriboAltura.setEditable(true);
      //txtEstribo.setEditable(true);
      txtEspacoEstribo.setEditable(true);

      txtIdProduto.setEditable(true);
      txtQtdeFerroColuna.setEditable(true);
      txtDataEntrega.setEditable(true);

      btnNovo.setEnabled(false);

      btnAlterar.setEnabled(false);
      btnBuscar.setEnabled(false);
      btnCancelar.setEnabled(true);
      btnDeletar.setEnabled(false);

      //     status = false;
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
      // TODO add your handling code here:
      //
      //estadoInicial();

      txtMensagem.setText("");
      txtMensagem.setText("Ferragem não sofreu alteração !");

      txtPedido.setText("");
      //txtUsuarioLogado.setText("");

      txtIdCliente.setText("");
      txtQtdeColunas.setText("");
      txtComprimentoColuna.setText("");
      txtEstriboLargura.setText("");
      txtEstriboAltura.setText("");
      //txtEstribo.setText("");
      txtEspacoEstribo.setText("");

      txtIdProduto.setText("");
      txtQtdeFerroColuna.setText("");
      txtDataEntrega.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtIdProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProdutoActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProdutoActionPerformed

  private void btnNovoFerragemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNovoFerragemActionPerformed
  {//GEN-HEADEREND:event_btnNovoFerragemActionPerformed
    // TODO add your handling code here:    

    txtQtdeColunas.setText("");
    txtComprimentoColuna.setText("");
    txtEstriboLargura.setText("");
    txtEstriboAltura.setText("");
    txtEspacoEstribo.setText("");

    txtIdProduto.setText("");
    txtQtdeFerroColuna.setText("");

    txtQtdeColunas.setEditable(true);
    txtComprimentoColuna.setEditable(true);
    txtEstriboLargura.setEditable(true);
    txtEstriboAltura.setEditable(true);
    txtEspacoEstribo.setEditable(true);

    txtIdProduto.setEditable(true);
    txtQtdeFerroColuna.setEditable(true);

    rbVergalhao.setSelected(true);
    rbVergalhaoAdicional.setEnabled(false);

    btnNovoFerragem.setEnabled(false);

  }//GEN-LAST:event_btnNovoFerragemActionPerformed

  private void txtObservacaoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtObservacaoActionPerformed
  {//GEN-HEADEREND:event_txtObservacaoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtObservacaoActionPerformed

  private double calculoTotalEstribo(double estriboAltura, double estriboLargura)
  {
    double xx = ((estriboAltura * 2) + (estriboLargura * 2) + 10);
    BigDecimal yy = new BigDecimal(xx);
    yy = yy.setScale(2, BigDecimal.ROUND_HALF_UP);
    double estriboTotal = yy.doubleValue();
    return estriboTotal;
  }

  private double calculoQtdeEstribos(double comprimento, double espacoEstribo, double qtdeFerragem)
  {
    double xx = ((comprimento / (espacoEstribo / 100)) * qtdeFerragem);
    BigDecimal yy = new BigDecimal(xx);
    yy = yy.setScale(2, BigDecimal.ROUND_HALF_UP);
    double qtdeEstribos = yy.doubleValue();
    return qtdeEstribos;
  }

  private double calculoQtdeBarrasColunas(double qtdeFerragem, double comprimento, int qtdeFerro)
  {
    double xx = (qtdeFerragem * comprimento * qtdeFerro) / 12;
    BigDecimal yy = new BigDecimal(xx);
    yy = yy.setScale(2, BigDecimal.ROUND_HALF_UP);
    double quantidadeBarrasColunas = yy.doubleValue();
    return quantidadeBarrasColunas;
  }

  private double calculoQtdeBarrasEstribos(double comprimento, double espacoEstribo, double qtdeFerragem, double estriboTotal)
  {
    double xx = ((comprimento / (espacoEstribo / 100) * qtdeFerragem) / (12 / (estriboTotal / 100)));
    BigDecimal yy = new BigDecimal(xx);
    yy = yy.setScale(2, BigDecimal.ROUND_HALF_UP);
    double quantidadeBarrasEstribos = yy.doubleValue();
    return quantidadeBarrasEstribos;
  }

  private double calculoQtdeArames(double comprimento, double espacoEstribo, double qtdeFerragem, double qtdeFerro)
  {
    double xx = ((comprimento / (espacoEstribo / 100) * qtdeFerragem) * (qtdeFerro / 200));
    BigDecimal yy = new BigDecimal(xx);
    yy = yy.setScale(2, BigDecimal.ROUND_HALF_UP);
    double quantidadeArames = yy.doubleValue();
    return quantidadeArames;

  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboStatus;
    private javax.swing.JButton btnAddProduto;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnNovoFerragem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JRadioButton rbArame;
    private javax.swing.JRadioButton rbEstribo;
    private javax.swing.JRadioButton rbVergalhao;
    private javax.swing.JRadioButton rbVergalhaoAdicional;
    private javax.swing.JTable tbFerragem;
    private javax.swing.JTable tbItemProduto;
    private javax.swing.JTextField txtComprimentoColuna;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDataEntrega;
    private javax.swing.JTextField txtDescricaoProduto;
    private javax.swing.JTextField txtEspacoEstribo;
    private javax.swing.JTextField txtEstriboAltura;
    private javax.swing.JTextField txtEstriboLargura;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdProduto;
    private javax.swing.JTextField txtMensagem;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtObservacao;
    private javax.swing.JFormattedTextField txtPedido;
    private javax.swing.JTextField txtQtdeColunas;
    private javax.swing.JTextField txtQtdeFerroColuna;
    // End of variables declaration//GEN-END:variables
}
